resources:
  - ./../base
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: eth1
  spec:
    template:
      spec:
        containers:
        - name: goeth
          resources:
            limits:
              cpu: "2000m"
              memory: "4096Mi"
            requests:
              cpu: "2000m"
              memory: "4096Mi"
- |-
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: default-storage
  provisioner: kubernetes.io/aws-ebs
  parameters:
    type: gp3
    iopsPerGB: "10"
    fsType: ext4