apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      eth1rpc:
        port: 8445
        # hostPort: 8000
        expose: true
        exposedPort: 8445
        # The port protocol (TCP/UDP)
        protocol: TCP
        # Use nodeport if set. This is useful if you have configured Traefik in a
        # LoadBalancer
        # nodePort: 32080
        # Port Redirections
        # Added in 2.2, you can make permanent redirects via entrypoints.
        # https://docs.traefik.io/routing/entrypoints/#redirection
        # redirectTo: websecure
      eth1p2ptcp:
        port: 30303
        expose: true
        exposedPort: 30303
        protocol: TCP
      eth1p2pudp:
        port: 30303
        expose: true
        exposedPort: 30303
        protocol: TCP
